### ISSUE TITLE
Please consider a less generic name and add a license file

### ISSUE THREAD

**Issue by unixorn** [heapbytes/heapbytes-zsh#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to heapbytes to match the plugin file

Also, please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!.

Thanks!

**Comment by heapbytes** [comment]
Heyy, do you want me to change the repo name to heapbytes? (i cannot do it for this repo since it's my github username i'll do it `heapbytes-zsh` instead.)
Thanks for consideration btw ^^

(if any further updates required do let me know)
