### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by kehiy** [heapbytes/heapbytes-zsh#3]
how can I install and use this theme?

**Comment by heapbytes** [comment]
1. You need to install oh-my-zsh
2. Paste the `heapbytes.zsh-theme` in `~/ .oh-my-zsh/custom/themes`
3. edit `~/.zshrc` and change the theme to heapbytes (refer : https://github.com/heapbytes/heapbytes-zsh/blob/main/.zshrc#L11)

**Comment by kehiy** [comment]
[oh-my-zsh] plugin 'zsh-autosuggestions' not found
[oh-my-zsh] plugin 'zsh-syntax-highlighting' not found

┌─[ ~] [ No IP] 
└─➜        

how can I fix it?
first the plugins and second the no ip and icons

**Comment by heapbytes** [comment]
you'll need to install those plugings & ig you are on virtual machine so in the .zsh-theme file you can put the interface name (can u give me ifconfig cmd ss so i can assist you for `No-Ip` thing)

ref here: 
`zsh-autosuggestions` -> https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
`zsh-syntax-highlighting` -> https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md

**Comment by kehiy** [comment]
@heapbytes it is fixed, thank you so much for your help bro.

About No IP, I removed this part, it makes the terminal a little confusing for me.
