### ISSUE TITLE
how to adjust get_ip_address for macOS

### ISSUE THREAD

**Issue by EtzBetz** [heapbytes/heapbytes-zsh#4]
Hey there!

Awesome theme, first to say! I wanted to use the get_ip_address() stuff as well on my theme, but I noticed that the if statement does not work out on macOS.
When I have an IP address, all is fine, but the if statement will also assert to true if the interface exists but there is no connection. On Linux it seems there will be no return and that's why -n works out?

Could you give me some assistance there? :)

<img width="1582" alt="image" src="https://github.com/heapbytes/heapbytes-zsh/assets/12349529/860508dc-9626-459a-8661-e56212e28832">

**Comment by EtzBetz** [comment]
This is how I fixed it now.
```bash
get_ip_address() {
  if [[ -n "$(networksetup -getinfo Wi-Fi | grep 'Subnet mask: ')" ]]; then
    echo "$(ifconfig en0 | awk '/inet / {print $2}')%{$reset_color%}"
  else
    echo "%{$bg_bold[red]%} No IP %{$reset_color%}"
  fi
}
```

**Comment by heapbytes** [comment]
Heyy, nice, can you create a pr....create heapbytes-mac.zsh-theme file, i've recevied dm of few mac os crowd, it will be easier for them to pull from here........also does the wifi icon worked for you?

**Comment by EtzBetz** [comment]
I can, but in my solution i left out the VPN stuff. And I can't really bother about including that, since I never use a VPN.
The WiFi Icon works for me kind of. It is displayed, since I have am using JetBrains Mono with Nerdfonts (installed via homebrew). But for some reasons the Icons all are displayed too small for me, so with the WiFi symbol the spacing is missing, its more or less the triangle.
